services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=books
    volumes:
      - ./data/mongo:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=books
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=example
    depends_on:
      - mongo
  storage:
    image: redis
    restart: always
    volumes:
      - ./data:/data
  counter:
    image: nikita140294/counter
    ports:
      - 5001:5001
    depends_on:
      - storage
    environment:
      - PORT=5001
      - REDIS_URL=redis://storage
  library:
    image: nikita140294/library
    ports:
      - 5000:5000
    depends_on:
      - counter
      - mongo
    environment:
      - PORT=5000
      - COUNTER_APP_URL=http://counter:5001
      - DB_URL=mongodb://root:example@mongo:27017